use_frameworks!

platform :ios, '15.0'

inhibit_all_warnings!

target 'XSCore_Example' do
  pod 'XSCore', :path => '../'

  target 'XSCore_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end
